version: '3.7'
services:
    chisco-core-db:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
            - APP_USER=$APP_USER
            - APP_PWD=$APP_PWD
            - DB_NAME=$DB_NAME
            - DB_COLLECTION_NAME=$DB_COLLECTION_NAME
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
        volumes:
            - ./data:/data/db
            - './scripts/:/docker-entrypoint-initdb.d/'
        ports:
            - '27017:27017'
        restart: always
