version: '3.7'
services:
    chisco-core-db:
        image: mongo
        network_mode: host
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
        volumes:
            - ./data:/data/db
            - './scripts/:/docker-entrypoint-initdb.d/'
        ports:
            - '27017:27017'
        restart: always
