version: '3.7'
services:
    chisco-core-db:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
        volumes:
            - ./script/init/:/docker-entrypoint-initdb.d
            - ./script/init:/home/mongodb
            - ./script/seed/:/home/mongodb/seed
            - ./data:/data/db
        ports:
            - '27017:27017'
        restart: always
